{
 "title": "Windows Exporter Dashboard",
 "description": "Windows Exporter Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "60s" },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(windows_cpu_time_total, instance)"
   },
   {
    "name": "socket_count",
    "label": "Sockets",
    "query": {
     "query": "query_result(scalar(count(windows_cpu_info{instance=\"$server\"})))"
    }
   },
   {
    "name": "cpu_model",
    "label": "CPU model",
    "query": {
     "query": "label_values(windows_cpu_info{instance=\"$server\"},name)"
    }
   },
   {
    "name": "threads_per_core",
    "label": "Threads per core",
    "query": {
     "query": "query_result(scalar(avg(windows_cpu_info_thread{instance=\"$server\"} / windows_cpu_info_core{instance=\"$server\"})))"
    }
   },
   {
    "name": "cores_per_socket",
    "label": "Cores per socket",
    "query": {
     "query": "query_result(scalar(avg(windows_cpu_info_core{instance=\"$server\"})))"
    }
   },
   {
    "name": "uptime",
    "label": "Uptime",
    "query": {
     "query": "query_result(scalar(windows_time_current_timestamp_seconds{instance=~\"$server\"} - ignoring(process, process_id) windows_process_start_time_seconds_timestamp{process_id=\"0\",instance=~\"$server\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "windows_time_current_timestamp_seconds{instance=~\"$server\"} - ignoring(process, process_id) windows_process_start_time_seconds_timestamp{process_id=\"0\",instance=~\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU active (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(windows_cpu_time_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Total net bandwidth",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(windows_net_bytes_total{instance=\"$server\"}[1m])) > 1)* 8"
    }
   ]
  },
  {
   "title": "Memory used (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((windows_memory_physical_total_bytes{instance=~\"$server\"} - windows_memory_physical_free_bytes{instance=~\"$server\"}) / windows_memory_physical_total_bytes{instance=~\"$server\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk usage (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((sum(windows_logical_disk_size_bytes{volume!~\"Harddisk.*\", instance=\"$server\"}) by (instance) - sum(windows_logical_disk_free_bytes{volume!~\"Harddisk.*\", instance=\"$server\"}) by (instance)) / sum(windows_logical_disk_size_bytes{volume!~\"Harddisk.*\", instance=\"$server\"}) by (instance) * 100)"
    }
   ]
  },
  { "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 } },
  {
   "title": "Disk free per volume (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(windows_logical_disk_free_bytes{instance=~\"$server\", volume!~\"HarddiskVolume.+\"} / windows_logical_disk_size_bytes{instance=~\"$server\", volume!~\"HardDiskVolume.+\"}) * 100",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Logical CPUs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "scalar(windows_cpu_logical_processor{instance=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Physical memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_memory_physical_total_bytes{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "CPU time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (mode) (rate(windows_cpu_time_total{instance=~\"$server\"}[60s]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{mode}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 } },
  {
   "title": "CPU usage (active%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg without (cpu) (sum(irate(windows_cpu_time_total{instance=\"$server\",mode!=\"idle\"}[5m])) by (mode)) / 16)* 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Net I/O per hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(windows_net_bytes_received_total{instance=\"$server\"}[1h])) by (instance)",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(increase(windows_net_bytes_sent_total{instance=\"$server\"}[1h])) by (instance)",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Net discard/err packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_outbound_discarded_total{instance=~\"$server\"}[$interval]) + irate(windows_net_packets_outbound_errors_total{instance=~\"$server\"}[$interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "TX",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_outbound_discarded_total{instance=~\"$server\"}[$interval]) + irate(windows_net_packets_outbound_errors_total{instance=~\"$server\"}[$interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "RX",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "NIC link speed",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_net_current_bandwidth_bytes{instance=\"$server\"} * 8",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "Network interfaces",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 24 },
   "targets": [
    {
     "expr": "sum without(family, job, instance, address, friendly_name, nic) (\r\n  label_replace(\r\n    label_replace(\r\n      label_replace(\r\n        windows_net_nic_address_info{instance=\"$server\"},\r\n        \"Address\", \"$1\", \"address\", \"(.*)\"\r\n      ),\r\n      \"Interface\", \"$1\", \"friendly_name\", \"(.*)\"\r\n    ),\r\n  \"NIC\", \"$1\", \"nic\", \"(.*)\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network traffic (bytes TX/RX)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_net_bytes_sent_total{instance=~\"$server\"}[$interval]) >0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}} (TX)",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "rate(windows_net_bytes_received_total{instance=~\"$server\"}[$interval]) >0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}} (RX)",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Disk I/O ops (60s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_logical_disk_split_ios_total{instance=~\"$server\", volume !~\"HarddiskVolume.+\"}[60s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "I/O on {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Disk queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "windows_logical_disk_requests_queued{instance=~\"$server\", volume!~\"HarddiskVolume.+\"}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Disk free (bytes, per volume)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_free_bytes{instance=~\"$server\", volume!~\"HarddiskVolume.+\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{volume}} free",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "windows_logical_disk_size_bytes{instance=~\"$server\",volume!~\"HarddiskVolume.+\"}",
     "legendFormat": "{{volume}} total"
    }
   ]
  },
  {
   "title": "Disk I/O (RW)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_write_bytes_total{instance=~\"$server\", volume !~\"HarddiskVolume.+\"}[60s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "- irate(windows_logical_disk_read_bytes_total{instance=~\"$server\", volume !~\"HarddiskVolume.+\"}[60s])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(windows_process_info{instance=\"$server\"})",
     "legendFormat": "Processes"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(windows_process_threads{instance=~\"$server\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Threads ",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Per-process CPU usage (60s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by(instance, process, process_id) (rate(windows_process_cpu_time_total{instance=\"$server\", process!=\"Idle\"}[60s]))\r\n / on(instance) group_left sum by(instance) (rate(windows_cpu_time_total{instance=\"$server\"}[60s])) > .00001",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Page faults per process (60s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "rate(windows_process_page_faults_total{instance=\"$server\"}[60s]) > 10",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Total I/O operations per process (60s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(windows_process_io_operations_total{instance=\"$server\"}[60s]) > 5",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Process working set size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "windows_process_working_set_bytes{instance=\"$server\"} > 1024*1024",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "NTP offset",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_time_computed_time_offset_seconds{instance=\"$server\"}",
     "legendFormat": "{{ instance}}"
    }
   ]
  },
  {
   "title": "Services by state",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(windows_service_state{instance=~\"$server\"}) by (state)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "__auto",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Volume capacity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_size_bytes{instance=~\"$server\", volume!~\"HarddiskVolume.+\"}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Sockets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(count(windows_cpu_info{instance=\"$server\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cores per socket",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(avg(windows_cpu_info_core{instance=\"$server\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads per core",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(avg(windows_cpu_info_thread{instance=\"$server\"} / windows_cpu_info_core{instance=\"$server\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU model",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, windows_cpu_info{instance=~\"$server\"})",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}